## 前端异常分类

### 一：代码错误

1. 语法错误

   开发阶段处理

2. 运行时错误

   - 同步异常

     try-catch捕获

     ```javascript
     // try-catch可以捕获同步运行时错误，不能捕获语法错误和异步错误
     console.log('开始');
     
     try{
         let name='eric';
         console.log(nae);
     }catch(e){
         console.log('try-catch捕获到同步运行时异常：',e);
     }
     
     try{
         setTimeout(() => {
             undefined.map(v => v);
           }, 1000);
     }catch(e){
         console.log('try-catch捕获到异步异常：',e);
     }
     ```

     window.onerror捕获

     ```javascript
     // window.onerror可以捕获同步运行时错误，异步错误；不能捕获语法错误、资源错误（比如静态资源或脚本或接口）、promise错误
     // 注意1：window.onerror 函数只有在返回 true 的时候，异常才不会向上抛出
     // 注意2：onerror 最好写在所有 JS 脚本的前面，否则有可能捕获不到错误
     window.onerror = function(message, source, lineno, colno, error) {
         // message：错误信息（字符串）。
         // source：发生错误的脚本URL（字符串）
         // lineno：发生错误的行号（数字）
         // colno：发生错误的列号（数字）
         // error：Error对象（对象）
         // console.log(`window.onerror捕获到${message}异常`,{message, source, lineno, colno, error});
         console.log('window.onerror捕获到异常',{message, source, lineno, colno, error});
         return true;
         };
     ```

     Vue.config.errorHandler捕获

   - 异步异常

     window.onerror捕获

   - promise异常

     catch捕获

     ```javascript
     let p=new Promise((resolve, reject)=>{
         setTimeout(() => {
             console.log('执行完成');
             reject(123);
         }, 1000);
     });
     p.catch((data)=>{
         console.log(data+1);
     })
     ```

     window.addEventListener捕获

     ```javascript
     // 没有写 catch 的 Promise 中抛出的错误无法被 onerror 或 try-catch 捕获到
     // 全局增加一个对 unhandledrejection 的监听，用来全局监听Uncaught Promise Error
     window.addEventListener("unhandledrejection", function(e){
         e.preventDefault()
         console.log('window.addEventListener捕获到unhandledrejection异常：', e);
         return true;
       });
     let p=new Promise((resolve, reject)=>{
         setTimeout(() => {
             console.log('执行完成');
             reject(123);
         }, 1000);
     });
     ```

     

   - 跨域 Script error

   - 崩溃和卡顿

### 二：资源加载错误

```javascript
// window.addEventListener可以捕获资源加载异常
// 注意1：不同浏览器下返回的 error 对象可能不同，需要注意兼容处理
// 注意2：需要注意避免 addEventListener 重复监听
window.addEventListener('error', (error) => {
    console.log('window.addEventListener捕获到error异常：', error);
}, true)
```

## 错误上报

### 一：利用Image对象发送请求

优点：

1. 所有浏览器都支持 Image 对象，包括那些不支持 XMLHttpRequest 对象的浏览器
2. 可以避免跨域限制。通常都是一台服务器要负责处理多台服务器的错误，而这种情况下使用 XMLHttpRequest 是不行的
3. 在记录错误的过程中出问题的概率比较低。大多数 Ajax 通信都是由 JavaScript 库提供的包装函 数来处理的，如果库代码本身有问题，而你还在依赖该库记录错误，可想而知，错误消息是不 可能得到记录的

```javascript
function logError(sev, msg){
     var img = new Image(); 
     img.src = "log.php?sev=" + encodeURIComponent(sev) + "&msg=" + encodeURIComponent(msg);
 } 
```

